-- to show the databases
show databases;




-- updating the data
UPDATE shop SET NAME_ = "Badrinath" WHERE CITY = "ANANTAPUR";
-- UPDATING WHOLE COLOMN NAMES
UPDATE shop SET NAME_ = "GANESH";
-- UPDATING SPECIFIC DATA using where key word
UPDATE SHOP SET NAME_ = "BHARATH" WHERE salesman_id = 2001;
UPDATE SHOP SET NAME_ = "rajesh" WHERE city ="hyderabad";


SELECT * FROM shop;


-- updates a box using two colomns
UPDATE SHOP SET NAME_ = "NAVEEEN " WHERE CITY = "BANGALUR" AND SALESMAN_ID = 2005;



CREATE TABLE TEST(salesman_id int PRIMARY KEY,NAME_ VARCHAR(20),CITY VARCHAR(30), COMMISSION INT(10));
-- COPYING THE WHOLE TABLE SO THAT NEW EMPTY TABLE BETTER TO HAVE THE SAME COLOMN NAMES AND SAME COLOMNS
INSERT INTO TEST SELECT *  FROM shop;  
SELECT * FROM TEST;




-- truncate IS DELETING THE DATA IN THE TABLE NOT THE SCHEMA
TRUNCATE TABLE TEST;

-- DELETE THE ENTIRE ROW
DELETE FROM SHOP WHERE NAME_ = "GANESH";


-- DROP will delete the entire table
DROP TABLE PUR;
DROP TABLE HERO;

-- ALTER // changing the table name
ALTER TABLE SHOP RENAME COLUMN salesman_id to id;
ALTER TABLE SHOP RENAME TO SHOPPING;
SELECT * FROM SHOPPING;



-- DELETEING THE WHOLE DATABASE
DROP DATABASE FILE2;
DROP DATABASE FILE;
DROP DATABASE CITY;
DROP DATABASE LIBRARY;


-- ADDING NEW COLUMN ADD ADDING DATA SPECIFIC ROW
ALTER TABLE SHOPPING ADD MOBILE INT(30);
UPDATE SHOPPING SET MOBILE = 34232423 WHERE NAME_ = "BHARATH";

-- CHANGE THE SIZE OF THE DATATYPE
ALTER TABLE SHOPPING MODIFY COLUMN MOBILE INT(40);




INSERT INTO SHOPPING VALUES(2003,"RAJU","KADIRI",0.98,6334443);
INSERT INTO SHOPPING VALUES(2006,"GANESH","PULIVENDULA",0.38,63434443);
INSERT INTO SHOPPING VALUES(2007,"JAGAN","CHITTUR",0.54,63343);
INSERT INTO SHOPPING VALUES(2002,"HARI","ANANTAPUR",0.93,63443);


-- DELETE SPECIFIC COLOMN
ALTER TABLE SHOPPING DROP COLUMN COMMISSION;
SELECT * FROM SHOPPING;




-- USING MIN AND MAX
SELECT MAX(ID) FROM SHOPPING;
SELECT MIN(ID) FROM SHOPPING;
-- USING SUM
SELECT SUM(ID) AS TOTAL FROM SHOPPING;

